# ADDED BY imprint (glvov) -- Unitree H1-2 embodiment for SONIC. Not upstream code.
"""Unitree **H1-2** (27 DOF / 28 bodies) embodiment for SONIC.

NAMING TRAP: this is the Unitree **H1-2**, which is a *different robot* from the
Unitree **H2** in ``h2.py``.  Do not copy numbers between the two files.

Assets
------
``data/assets/robot_description/urdf/h1_2/h1_2.urdf`` and
``data/assets/robot_description/mjcf/h1_2.xml`` are both GENERATED by
``gear_sonic/scripts/gen_h1_2_assets.py`` from our r13 USD factory's blessed
no-fingers source (ProtoMotions ``h1_2_box_feet.xml``, the exact
primitive-collision model our H1-2 tracker policy was trained on).  No vendor
URDF is in this path -- see that script's docstring for the provenance argument.

The only structural delta vs. our canonical model is that the massless marker
body ``head_aux`` is dropped, so that ``num_bodies == num_dof + 1`` as SONIC's
order converter requires.  Its constant offset is preserved below as
``H1_2_HEAD_OFFSET_IN_TORSO`` so head-referenced rewards stay expressible.

Index tables
------------
The five tables below are GENERATED by
``gear_sonic/scripts/gen_h1_2_order_tables.py`` and frozen here as literals.
Do not hand-edit; re-run the generator (``--check`` fails the build if these
literals drift from the assets).  That script also proves its convention by
reproducing upstream's own published H2 tables from ``h2.xml`` + ``h2.py``, and
cross-checks the derived Isaac Lab order against the *independently measured*
order frozen in our r13 USD factory.

Semantics (same as G1/H2; note PR #112's ``x2_ultra.py`` names its constants the
other way round and swaps them in the dict):

    ISAACLAB_TO_MUJOCO_*[k] = IsaacLab index of the k-th MuJoCo entry
    MUJOCO_TO_ISAACLAB_*[i] = MuJoCo index of the i-th IsaacLab entry
"""

from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg
import isaaclab.sim as sim_utils

ASSET_DIR = "gear_sonic/data/assets"

# --------------------------------------------------------------------------- #
# Actuator parameters
#
# These are OUR measured/tuned H1-2 values, taken from
# ``ProtoMotions/protomotions/robot_configs/h1_2.py`` (which is what the live
# H1-2 WBC teacher trains with).  They already satisfy SONIC's own formulas
#
#     STIFFNESS = ARMATURE * NATURAL_FREQ**2
#     DAMPING   = 2 * DAMPING_RATIO * ARMATURE * NATURAL_FREQ
#
# at NATURAL_FREQ = 10 Hz and DAMPING_RATIO = 2.0 -- both stacks descend from
# BeyondMimic -- so nothing had to be reconciled away.  What differs from
# G1/H2/X2 is only the per-joint ARMATURE (H1-2 uses different motors), which is
# exactly the quantity the guide says to take from the robot's own datasheet.
#
# ARM GROUP = PRODUCTION VALUES, NOT THE CHECKED-IN DEFAULTS.
# Our ProtoMotions ``robot_configs/h1_2.py`` computes the arm group through
# env gates (``PM_ARM_KP``/``PM_ARM_KD``/``PM_ARM_EFFORT_<GROUP>``) whose
# in-file defaults (KP 19.74, KD 1.26, effort 40/18/18/19) are the *unconfigured
# fallback*.  Our canonical launcher always sets them, and the live v58 teacher
# (``mm_logs/canonical_teacher_20260806_v58/launch_v58.sh``) is training right
# now with KP 40, KD 2.0, shoulder 120, elbow 120, wrist 30.  Those production
# values are what is baked in below, so the SONIC robot matches the teacher we
# will be comparing against.
#
# Note ``_arm_effort("SHOULDER", 18)`` supplies shoulder *yaw* as well, and it
# reads the same ``PM_ARM_EFFORT_SHOULDER``.  So production gives shoulder yaw
# 120 too -- not the 18 N-m default.  Mirrored exactly here rather than invented.
#
# KNOWN DISCREPANCY (recorded deliberately, do not "fix" silently): production's
# arm triple no longer satisfies SONIC's own KP/KD/armature formulas.  With
# armature 0.005 the formula gives KP 19.74 / KD 1.26; with KP pinned at 40 the
# implied armature is 0.010133 and the zeta=2.0 damping would be 2.547.
# Production runs KD 2.0 against armature 0.005 -- i.e. zeta ~= 3.18 w.r.t. the
# declared armature, or ~1.57 w.r.t. the KP-implied armature.  Kept at 2.0 for
# comparability with the teacher.
# --------------------------------------------------------------------------- #
import os

NATURAL_FREQ = 10 * 2.0 * 3.1415926535  # 10 Hz
DAMPING_RATIO = 2.0

ARMATURE_300 = 0.040  # knee (300 N-m class)
ARMATURE_200 = 0.030  # hips + torso (200 N-m class)
ARMATURE_60 = 0.010  # ankle pitch (60 N-m class), doubled below
ARMATURE_40 = 0.005  # arms + ankle roll (40 N-m class), doubled for ankle roll

STIFFNESS_300 = ARMATURE_300 * NATURAL_FREQ**2
STIFFNESS_200 = ARMATURE_200 * NATURAL_FREQ**2
STIFFNESS_60 = ARMATURE_60 * NATURAL_FREQ**2
STIFFNESS_40 = ARMATURE_40 * NATURAL_FREQ**2

DAMPING_300 = 2.0 * DAMPING_RATIO * ARMATURE_300 * NATURAL_FREQ
DAMPING_200 = 2.0 * DAMPING_RATIO * ARMATURE_200 * NATURAL_FREQ
DAMPING_60 = 2.0 * DAMPING_RATIO * ARMATURE_60 * NATURAL_FREQ
DAMPING_40 = 2.0 * DAMPING_RATIO * ARMATURE_40 * NATURAL_FREQ

# --- arm group: production values, with the same env gates our launcher uses,
# so a SONIC run under the canonical launcher env stays identical to the teacher.
def _arm_effort(group: str, production: float) -> float:
    v = os.environ.get(f"PM_ARM_EFFORT_{group}") or os.environ.get("PM_ARM_EFFORT")
    return float(v) if v else production


ARM_STIFFNESS = float(os.environ.get("PM_ARM_KP") or 40.0)
ARM_DAMPING = float(os.environ.get("PM_ARM_KD") or 2.0)
ARM_ARMATURE = float(os.environ.get("PM_ARM_ARMATURE") or ARMATURE_40)
ARM_EFFORT_SHOULDER_PR = _arm_effort("SHOULDER", 120.0)
ARM_EFFORT_SHOULDER_YAW = _arm_effort("SHOULDER", 120.0)  # same gate as SHOULDER_PR
ARM_EFFORT_ELBOW = _arm_effort("ELBOW", 120.0)
ARM_EFFORT_WRIST = _arm_effort("WRIST", 30.0)

# H1-2 has no head link: the head is a fixed collision capsule on ``torso_link``
# and our canonical MJCF marks its frame with a massless ``head_aux`` body at
# this offset in the torso frame.  Kept so head-referenced terms can be written
# as torso_link + offset instead of needing a body that Isaac would merge away.
H1_2_HEAD_OFFSET_IN_TORSO = (0.0, 0.0, 0.7)

# SONIC's own mechanism for virtual/marker bodies.  Measured, and verified to
# keep fk_batch's dof_pos at 27 on this 28-body asset (see
# tests/test_h1_2_embodiment.py::T6).  Left DISABLED in sonic_h1_2.yaml because
# motion_lib_base.py:1506-1507 has the `global_translation_extend` consumption
# commented out upstream, so today it would deliver no head data while still
# widening `num_bodies_augment` to 29 and thus every aux-loss decoder/normalizer.
# Wire it in when the extended-body consumption is enabled.
H1_2_HEAD_EXTEND_CONFIG = [
    {
        "joint_name": "head_aux",
        "parent_name": "torso_link",
        "pos": list(H1_2_HEAD_OFFSET_IN_TORSO),
        "rot": [1.0, 0.0, 0.0, 0.0],
    }
]

# ==== BEGIN GENERATED: gear_sonic/scripts/gen_h1_2_order_tables.py ==========
H1_2_ISAACLAB_JOINTS = [
    "pelvis",
    "left_hip_yaw_link",
    "right_hip_yaw_link",
    "torso_link",
    "left_hip_pitch_link",
    "right_hip_pitch_link",
    "left_shoulder_pitch_link",
    "right_shoulder_pitch_link",
    "left_hip_roll_link",
    "right_hip_roll_link",
    "left_shoulder_roll_link",
    "right_shoulder_roll_link",
    "left_knee_link",
    "right_knee_link",
    "left_shoulder_yaw_link",
    "right_shoulder_yaw_link",
    "left_ankle_pitch_link",
    "right_ankle_pitch_link",
    "left_elbow_link",
    "right_elbow_link",
    "left_ankle_roll_link",
    "right_ankle_roll_link",
    "left_wrist_roll_link",
    "right_wrist_roll_link",
    "left_wrist_pitch_link",
    "right_wrist_pitch_link",
    "left_wrist_yaw_link",
    "right_wrist_yaw_link",
]

H1_2_ISAACLAB_TO_MUJOCO_DOF = [
    0, 3, 7, 11, 15, 19, 1, 4,
    8, 12, 16, 20, 2, 5, 9, 13,
    17, 21, 23, 25, 6, 10, 14, 18,
    22, 24, 26,
]

H1_2_MUJOCO_TO_ISAACLAB_DOF = [
    0, 6, 12, 1, 7, 13, 20, 2,
    8, 14, 21, 3, 9, 15, 22, 4,
    10, 16, 23, 5, 11, 17, 24, 18,
    25, 19, 26,
]

H1_2_ISAACLAB_TO_MUJOCO_BODY = [
    0, 1, 4, 8, 12, 16, 20, 2,
    5, 9, 13, 17, 21, 3, 6, 10,
    14, 18, 22, 24, 26, 7, 11, 15,
    19, 23, 25, 27,
]

H1_2_MUJOCO_TO_ISAACLAB_BODY = [
    0, 1, 7, 13, 2, 8, 14, 21,
    3, 9, 15, 22, 4, 10, 16, 23,
    5, 11, 17, 24, 6, 12, 18, 25,
    19, 26, 20, 27,
]
# ==== END GENERATED =========================================================

H1_2_ISAACLAB_TO_MUJOCO_MAPPING = {
    "isaaclab_joints": H1_2_ISAACLAB_JOINTS,
    "isaaclab_to_mujoco_dof": H1_2_ISAACLAB_TO_MUJOCO_DOF,
    "mujoco_to_isaaclab_dof": H1_2_MUJOCO_TO_ISAACLAB_DOF,
    "isaaclab_to_mujoco_body": H1_2_ISAACLAB_TO_MUJOCO_BODY,
    "mujoco_to_isaaclab_body": H1_2_MUJOCO_TO_ISAACLAB_BODY,
}


# H1-2 Robot Configuration
H1_2_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        fix_base=False,
        replace_cylinders_with_capsules=True,
        asset_path=f"{ASSET_DIR}/robot_description/urdf/h1_2/h1_2.urdf",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0, damping=0)
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        # Canonical H1-2 root height is 1.03 m at the zero pose (our MJCF spawns
        # the pelvis there).  The mild crouch below lowers the pelvis ~1 cm, so
        # 1.05 leaves ~2 cm of foot clearance on frame 1.
        pos=(0.0, 0.0, 1.05),
        joint_pos={
            ".*_hip_pitch_joint": -0.15,
            ".*_knee_joint": 0.30,
            ".*_ankle_pitch_joint": -0.15,
            ".*_elbow_joint": 0.30,
            "left_shoulder_roll_joint": 0.20,
            "right_shoulder_roll_joint": -0.20,
        },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                ".*_hip_yaw_joint",
                ".*_hip_roll_joint",
                ".*_hip_pitch_joint",
                ".*_knee_joint",
            ],
            effort_limit_sim={
                ".*_hip_yaw_joint": 200.0,
                ".*_hip_roll_joint": 200.0,
                ".*_hip_pitch_joint": 200.0,
                ".*_knee_joint": 300.0,
            },
            velocity_limit_sim=50.0,
            stiffness={
                ".*_hip_yaw_joint": STIFFNESS_200,
                ".*_hip_roll_joint": STIFFNESS_200,
                ".*_hip_pitch_joint": STIFFNESS_200,
                ".*_knee_joint": STIFFNESS_300,
            },
            damping={
                ".*_hip_yaw_joint": DAMPING_200,
                ".*_hip_roll_joint": DAMPING_200,
                ".*_hip_pitch_joint": DAMPING_200,
                ".*_knee_joint": DAMPING_300,
            },
            armature={
                ".*_hip_yaw_joint": ARMATURE_200,
                ".*_hip_roll_joint": ARMATURE_200,
                ".*_hip_pitch_joint": ARMATURE_200,
                ".*_knee_joint": ARMATURE_300,
            },
        ),
        "feet": ImplicitActuatorCfg(
            joint_names_expr=[".*_ankle_pitch_joint", ".*_ankle_roll_joint"],
            effort_limit_sim={
                ".*_ankle_pitch_joint": 60.0,
                ".*_ankle_roll_joint": 40.0,
            },
            velocity_limit_sim=50.0,
            stiffness={
                ".*_ankle_pitch_joint": 2.0 * STIFFNESS_60,
                ".*_ankle_roll_joint": 2.0 * STIFFNESS_40,
            },
            damping={
                ".*_ankle_pitch_joint": 2.0 * DAMPING_60,
                ".*_ankle_roll_joint": 2.0 * DAMPING_40,
            },
            armature={
                ".*_ankle_pitch_joint": 2.0 * ARMATURE_60,
                ".*_ankle_roll_joint": 2.0 * ARMATURE_40,
            },
        ),
        # H1-2's single waist DOF is spelled ``torso_joint`` (no waist_* joints).
        "torso": ImplicitActuatorCfg(
            joint_names_expr=["torso_joint"],
            effort_limit_sim=200.0,
            velocity_limit_sim=50.0,
            stiffness=STIFFNESS_200,
            damping=DAMPING_200,
            armature=ARMATURE_200,
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=[
                ".*_shoulder_pitch_joint",
                ".*_shoulder_roll_joint",
                ".*_shoulder_yaw_joint",
                ".*_elbow_joint",
                ".*_wrist_roll_joint",
                ".*_wrist_pitch_joint",
                ".*_wrist_yaw_joint",
            ],
            effort_limit_sim={
                ".*_shoulder_pitch_joint": ARM_EFFORT_SHOULDER_PR,
                ".*_shoulder_roll_joint": ARM_EFFORT_SHOULDER_PR,
                ".*_shoulder_yaw_joint": ARM_EFFORT_SHOULDER_YAW,
                ".*_elbow_joint": ARM_EFFORT_ELBOW,
                ".*_wrist_roll_joint": ARM_EFFORT_WRIST,
                ".*_wrist_pitch_joint": ARM_EFFORT_WRIST,
                ".*_wrist_yaw_joint": ARM_EFFORT_WRIST,
            },
            velocity_limit_sim=50.0,
            stiffness=ARM_STIFFNESS,
            damping=ARM_DAMPING,
            armature=ARM_ARMATURE,
        ),
    },
)

# H1-2 Action Scale.  Same 0.25 * effort / stiffness form used by g1.py, h2.py
# and PR #112's x2_ultra.py.  (The prose in new_embodiments.md omits the 0.25;
# every implementation in the tree has it, so the code is followed here.)
H1_2_ACTION_SCALE = {}
for a in H1_2_CFG.actuators.values():
    e = a.effort_limit_sim
    s = a.stiffness
    names = a.joint_names_expr
    if not isinstance(e, dict):
        e = dict.fromkeys(names, e)
    if not isinstance(s, dict):
        s = dict.fromkeys(names, s)
    for n in names:
        if n in e and n in s and s[n]:
            H1_2_ACTION_SCALE[n] = 0.25 * e[n] / s[n]
